<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="System.Reactive" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\pipe\WhereIsIt.Pipe.Client\WhereIsIt.Pipe.Client.csproj" />
  </ItemGroup>
</Project>
